<?php
// Generated automatically by daogen.
// Do NOT edit this file.
// Any changes made to this file will be overwritten the next time it is generated.

class Category {
	public $id;
	public $name;
	public $description;
	public $isvisible;

	public function defaultAllFields() {
		$this->id = null;
		$this->name = null;
		$this->description = null;
		$this->isvisible = null;
	}

	public function loadFromArray($arr) {
		$this->id = isset($arr['id']) ? (int)$arr['id'] : null;
		$this->name = isset($arr['name']) ? (string)$arr['name'] : null;
		$this->description = isset($arr['description']) ? (string)$arr['description'] : null;
		$this->isvisible = isset($arr['isvisible']) ? (int)$arr['isvisible'] : null;
		return $this;
	}
}
