<?php
// Generated automatically by daogen.
// Do NOT edit this file.
// Any changes made to this file will be overwritten the next time it is generated.

class Products {
	public $id;
	public $productid;
	public $name;
	public $description;
	public $ingredients;
	public $price;
	public $weight;
	public $category;
	public $isvisible;
	public $sequence;

	public function defaultAllFields() {
		$this->id = null;
		$this->productid = null;
		$this->name = null;
		$this->description = null;
		$this->ingredients = null;
		$this->price = null;
		$this->weight = null;
		$this->category = null;
		$this->isvisible = null;
		$this->sequence = null;
	}

	public function loadFromArray($arr) {
		$this->id = isset($arr['id']) ? (int)$arr['id'] : null;
		$this->productid = isset($arr['productid']) ? (string)$arr['productid'] : null;
		$this->name = isset($arr['name']) ? (string)$arr['name'] : null;
		$this->description = isset($arr['description']) ? (string)$arr['description'] : null;
		$this->ingredients = isset($arr['ingredients']) ? (string)$arr['ingredients'] : null;
		$this->price = isset($arr['price']) ? (double)$arr['price'] : null;
		$this->weight = isset($arr['weight']) ? (string)$arr['weight'] : null;
		$this->category = isset($arr['category']) ? (int)$arr['category'] : null;
		$this->isvisible = isset($arr['isvisible']) ? (int)$arr['isvisible'] : null;
		$this->sequence = isset($arr['sequence']) ? (int)$arr['sequence'] : null;
		return $this;
	}
}
